{{- /*
Copyright 2025 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}
{{- with .Values.elementAdmin -}}
{{- if and .enabled .gateway.enabled .gateway.host -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
{{- include "element-io.ess-library.gateway.annotations" (dict "root" $ "context" (dict "gateway" .gateway)) | nindent 2 }}
  labels:
    {{- include "element-io.element-admin.labels" (dict "root" $ "context" .) | nindent 4 }}
  name: {{ $.Release.Name }}-element-admin
  namespace: {{ $.Release.Namespace }}
spec:
  hostnames:
  - {{ (tpl .gateway.host $) | quote }}
{{- include "element-io.ess-library.gateway.parentRefs" (dict "root" $ "context" .gateway.parentRefs) | nindent 2 }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ $.Release.Name }}-element-admin
      port: {{ include "element-io.element-admin.ports" (dict "portName" "http") }}
{{- end }}
{{- end }}
